server.port=9090
spring.application.name=anz-java-code-challenge

# ===============================
# H2 DATABASE
# ===============================
spring.datasource.url=jdbc:h2:mem:ordersdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# SECURITY
# ===============================
spring.security.user.name=admin
spring.security.user.password=admin123

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ===============================
# ACTIVEMQ / JMS
# ===============================
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false
spring.jms.listener.concurrency=3

notification.queue.name=order.notification.queue

# ===============================  
# DEVTOOLS CONFIGURATION
# ===============================
# Enable DevTools restart even when running from JAR
spring.devtools.restart.enabled=true
# Additional DevTools settings
spring.devtools.livereload.enabled=true
